version: '3.2'
services:
  db:
    deploy:
      placement:
        constraints:
        - node.labels.jaggerdb == true
      replicas: 1
    environment:
      MYSQL_DATABASE: rr3
      MYSQL_PASSWORD: rr312
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rr3
    image: mariadb
    restart: always
    volumes:
    - db_data:/var/lib/mysql:rw
  jagger:
    depends_on:
    - db
    - rabbitmq
    environment:  
      JAGGER_MAILER: 1
      JAGGER_CRON: 1
      DB_HOST: db
      DB_PASSWORD: rr312
      DB_USER: rr3
#     DB_SSL: true
      MEMCACHE_HOST: memcache
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PASS: password
      RABBITMQ_USER: admin
      RABBITMQ_VHOST: /
      VIRTUAL_HOST: jagger.example.com
#     JAGGER_SYNC_PASS: randomstring
#     JAGGER_SETUP: true
    image: janul/jagger:2018052806
    links:
    - db
    - rabbitmq
    - redis
    - memcache
    ports:
    - published: 443
      target: 443
    secrets:
    - source: metasigner-cert
    - source: metasigner-key
    - source: metasigner-pass
    - source: https_ca
      target: https_ca.crt
    - source: https_crt
      target: https.crt
    - source: https_key
      target: https.key
#   - source: mysql_ca.crt
#   - source: mysql_client_src.crt
#     target: mysql_client.crt
#   - source: mysql_client_src.key
#     target: mysql_client.key
    volumes:
    - jagger_filescache:/opt/Jagger/application/cache:rw
    - jagger_config:/opt/Jagger/application/config:rw
    - jagger_logs:/opt/Jagger/application/logs:rw
    - jagger_signedmetadata:/opt/Jagger/signedmetadata:rw
  rabbitmq:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 1
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_ERLANG_COOKIE: foobar
      RABBITMQ_USE_LONGNAME: "false"
    image: rabbitmq:3.7.0
  redis:
    deploy:
      replicas: 1
    image: redis
  memcache:
    deploy:
      replicas: 1
    image: memcached
volumes:
  db_data: {}
  jagger_config: {}
  jagger_filescache: {}
  jagger_logs: {}
  jagger_signedmetadata: {}
secrets:
  metasigner-cert:
    external: true
  metasigner-key:
    external: true
  metasigner-pass:
    external: true
#  mysql_ca.crt:
#    external: true
#  mysql_client_src.crt:
#    external: true
#  mysql_client_src.key:
#    external: true
  https_ca: 
    external: true
  https_crt: 
    external: true
  https_key: 
    external: true

